seed: 123
test_size: 0.25
val_size: 0.25


project_root: ${oc.env:PROJECT_ROOT} #assume env. variable project_root set before

paths:
  folder:
    data: ${project_root}/data
    data_raw: ${paths.folder.data}/raw
    data_preprocessed: ${paths.folder.data}/preprocessed
    assets: ${project_root}/assets
    assets_importance: ${paths.folder.assets}/importance
    assets_effects: ${paths.folder.assets}/effects
    assets_plots: ${paths.folder.assets}/plots
    assets_plots_importance: ${paths.folder.assets_plots}/importance
    assets_plots_effects: ${paths.folder.assets_plots}/effects
    assets_plots_data: ${paths.folder.assets_plots}/data
    assets_conf: ${paths.folder.assets}/conf
    assets_conf_experiments: ${paths.folder.assets_conf}/experiments
    assets_conf_data: ${paths.folder.assets_conf}/data
    conf: ${project_root}/conf
    conf_inducer: ${paths.folder.conf}/inducer

  file:
    conf_data_openml: ${paths.folder.conf}/data/openml.yaml
    conf_data_simulation: ${paths.folder.conf}/data/simulation.yaml
