jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check package quality
        run: uvx pyroma .

  # test:
    # ... matrix for actual tests on multiple OS/Python versions